Wdp231101 14
odevpl/wdp2311 pull request #17
Opened 2023-11-09 19:19 UTC by riozshow

2023-11-14 17:20 UTC, RobertSynowiec requested changes
Ticket nie działa - brak możliwości uruchomienia strony.  Proszę popraw kod.

2023-11-14 19:41 UTC, riozshow commented
> Ticket nie działa - brak możliwości uruchomienia strony. Proszę popraw kod.

Zerknij prosze teraz. U mnie dziala ;)

2023-11-15 08:25 UTC, RobertSynowiec requested changes
W linii 112 plik NewFurniture.js:  występuje błąd Unexpected token (112:1).  
Brak możliwości uruchomienia projektu.

2023-11-16 07:13 UTC, RobertSynowiec requested changes
Dalej występują konflikty z masterem.

2023-11-16 09:43 UTC, riozshow commented
> Dalej występują konflikty z masterem.

Hej Robert. Nie widze tutaj konfliktow z plikami. Chodzi o cos innego?

2023-11-16 09:46 UTC, riozshow commented
> Dalej występują konflikty z masterem.

Jeszcze raz zrobilem pulla. Moze teraz pojdzie.

2023-11-16 12:08 UTC, RobertSynowiec requested changes

2023-11-16 12:08 UTC, RobertSynowiec commented on src/components/layout/MenuBar/MenuBar.js
>      </div>
Brak domknięcia diva

2023-11-16 13:26 UTC, RobertSynowiec approved these changes

2023-11-16 13:26 UTC, merged