create section Blog, add content and styles WDP231101-41
odevpl/wdp2311 pull request #39
Opened 2023-11-12 14:54 UTC by OlhaOvcharenko

Section has been created based on customer design.

2023-11-14 21:32 UTC, OlhaOvcharenko commented
> Ticket nie działa - brak możliwości otworzenia strony. Proszę popraw kod.

Poprawiłam, lokalnie działa, proszę o sprawdzenie :)

2023-11-15 09:46 UTC, RobertSynowiec requested changes
Brak możliwości uruchomienia projektu.
Błąd próby importu: „'Routes'” nie są eksportowane z „react-router-dom”.

2023-11-15 11:10 UTC, OlhaOvcharenko commented
> > Ticket nie działa - brak możliwości otworzenia strony. Proszę popraw kod.
> 
> Poprawiłam, lokalnie działa, proszę o sprawdzenie :)
![IMG_0226](https://github.com/odevpl/wdp2311/assets/134648751/3a59cfa4-a423-47c0-b351-33db2c2b89e1)
Przy ostatnim commicie Routes poprawiłam na Switch, dziwne u mnie lokalnie wszystko się odpala. Ale są konflikty, spróbuję poprawić konflikty , może wtedy pójdzie

2023-11-15 11:34 UTC, OlhaOvcharenko commented
> > Ticket nie działa - brak możliwości otworzenia strony. Proszę popraw kod.
> 
> Poprawiłam, lokalnie działa, proszę o sprawdzenie :) ![IMG_0226](https://user-images.githubusercontent.com/134648751/283097539-3a59cfa4-a423-47c0-b351-33db2c2b89e1.jpeg) Przy ostatnim commicie Routes poprawiłam na Switch, dziwne u mnie lokalnie wszystko się odpala. Ale są konflikty, spróbuję poprawić konflikty , może wtedy pójdzie

 Robert, będę miała dostęp do komputera tylko około 21:00 i odrazu zacznę od rozwiązania konfliktu, czy możemy jakos się dogadać ze tylko to poprawię wieczorem spróbujesz sprawdzić , dopóki nie pojawią sie nowe konflikty?czy będziesz miał czas na to?

2023-11-15 12:24 UTC, RobertSynowiec requested changes
Daj znać do 22 będę dostępny

2023-11-15 12:29 UTC, OlhaOvcharenko commented
> Daj znać do 22 będę dostępny

Oki, dziękuję

2023-11-15 19:54 UTC, OlhaOvcharenko commented
Robert, kolejna próba, proszę o sprawdzenie. Mój task był niżej niż task podstrona Bloga, ale podstrona Boga już została zmergowana więc w ogóle musiłą=am przerobić kod w ten sposób że dodałam eelement Section Blog

2023-11-15 20:40 UTC, RobertSynowiec approved these changes

2023-11-15 20:40 UTC, merged