WDP231101-46 Registration form - functionality and validation added
odevpl/wdp2311 pull request #70
Opened 2023-11-17 10:47 UTC by evka07

1. Registration form - functionality added
2. Registration form - validation added
3. Changed styles in Registration form

2023-11-17 12:22 UTC, Dominik-Wilk commented on src/components/views/Register/Register.js
W poleceniu również była informacja o dodaniu pola "imię" oraz "nazwisko". Pola te niestety nie zostały dodane. Proszę je dodać.

2023-11-17 12:22 UTC, Dominik-Wilk requested changes
W poleceniu również była informacja o dodaniu pola "imię" oraz "nazwisko". Pola te niestety nie zostały dodane. Proszę je dodać.

2023-11-17 12:24 UTC, evka07 commented
> W poleceniu również była informacja o dodaniu pola "imię" oraz "nazwisko". Pola te niestety nie zostały dodane. Proszę je dodać.

Tak, ale proszę zobaczyć zadanie [WDP231101-45](https://projects.kodilla.com/browse/WDP231101-45)

2023-11-17 12:25 UTC, evka07 commented
> > W poleceniu również była informacja o dodaniu pola "imię" oraz "nazwisko". Pola te niestety nie zostały dodane. Proszę je dodać.
> 
> Tak, ale proszę zobaczyć zadanie [WDP231101-45](https://projects.kodilla.com/browse/WDP231101-45)

https://kodillameet.pl/pg/rejestracja.png

2023-11-17 12:28 UTC, evka07 commented
> > > W poleceniu również była informacja o dodaniu pola "imię" oraz "nazwisko". Pola te niestety nie zostały dodane. Proszę je dodać.
> > 
> > 
> > Tak, ale proszę zobaczyć zadanie [WDP231101-45](https://projects.kodilla.com/browse/WDP231101-45)
> 
> https://kodillameet.pl/pg/rejestracja.png

Zadanie jest dodanie walidacji do formularza rejestracyjnego.

2023-11-17 17:20 UTC, evka07 commented
> W 46 również jest dodanie dwóch dodatkowych pól oraz ich walidacja

Przepraszam, zgadza się, tłumacz mnie zawiódł Zrobię, nie ma sprawy

2023-11-20 11:38 UTC, evka07 commented
WDP231101-46 Registration form - functionality and validation added, input name ans lastname added

2023-11-24 15:50 UTC, Dominik-Wilk approved these changes

2023-11-24 15:50 UTC, Dominik-Wilk approved these changes

2023-11-24 15:51 UTC, merged