Add RWD for section Brands WDP231101-32
odevpl/wdp2311 pull request #89
Opened 2023-11-21 19:24 UTC by ZosiaSzyposzynska

I added RWD for BrandsSlider

2023-11-21 20:03 UTC, OlhaOvcharenko requested changes
[WDP231101-32.docx](https://github.com/odevpl/wdp2311/files/13430497/WDP231101-32.docx)
Hej Zofia, opisałam wszystkie uwagi w pliku, proszę załączam go:)Jeśli będziesz miała jakiekolwiek pytania, proszę daj znać:)

2023-11-22 17:23 UTC, OlhaOvcharenko commented on src/components/features/BrandsSlider/BrandsSlider.js
> +      case 'TABLET':
Chciałabym zaproponować, aby również dla tabletów pozostawić 'col', ponieważ obecnie przy układzie Tablet elementy się rozjeżdżają  
![image](https://github.com/odevpl/wdp2311/assets/134648751/137f7623-d8ac-41f0-aeaf-c9f7b51032da)

2023-11-22 17:42 UTC, OlhaOvcharenko requested changes
Ogólnie jest dobrze :) Ale mam parę komentarzy. 
Pierwszy dotyczący RWD dla tabletów. Proszę  komentarz lin. 39. 


I kolejna rzecz to jest  ten element Swipeable. Dodałaś go, ale niestety funkcjonalność nie działa, czyli nie da się przesunąć slidów za pomocą swipe. Z tego, co widzę, dodałaś to z paczki React, ale mamy także element Swipeable w folderze 'Common'. Może lepiej spróbować skorzystać z niego. Jako przykład można użyć sekcji Feedback lub Promotional, gdzie już została zaimplementowana funkcjonalność Swipeable.

2023-11-23 18:49 UTC, ZosiaSzyposzynska commented
Hej, poprawiłam, dodałam funkcjonalność Swipeable, kropki są dwie na laptopie, bo zdjęć jest 9 a miało być 6 zdj na takiej szerokości, jak zmienimy szerokość na mniejszą to kropki są trzy itp itd. Dodałam style dla nich, Swipeable powinno już działać, dla tabletów zmieniłam na samo 'col' tak jak pisałaś, żeby się nie rozjeżdżało.

2023-11-23 20:16 UTC, OlhaOvcharenko commented
Hej,

RWD działa super! :)
Swipeable też działa ok, ale myślę że w sumie można otworzyć taska i pogodzić Swipeable ze zmianą slidów przy  klikach, to już nie dotyczy twojego zadania.

Jedynie o co chciałabym prosić to poprawić tu style, bo widzę że 2 razy urzyłaś 'styles.slider' i przez to utworzyła się dziwna podwójna ramka 
![image](https://github.com/odevpl/wdp2311/assets/134648751/36292979-4fdb-4afc-9872-03408f72d2f2)

Oraz 'const handleNext/handlePrev'  są takie same jak nextPage/previousPage. Więc którąś z nich można usunąć
![image](https://github.com/odevpl/wdp2311/assets/134648751/bddbe318-0678-4424-b283-e1a91df6e639)

I to tyle :)

2023-11-23 20:18 UTC, OlhaOvcharenko requested changes
Powyżej dodałam drobne poprawki

2023-11-24 19:09 UTC, merged